# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9fd9f2284e70880e1af6c43f5321a41bc0465589512b8d1212f595d7a1df3fed3d062e1da4d8619656139f5193bff924835e3df77069e3792392096d2dd6ff6

test:
  secret_key_base: c0c26e279aeb28b55ba1796ad9cef317202037150d56b4f59a994864671542776256c3efff5bf3cf97a19430acc933595a53ae65cf18a51d61d36ff921bd4cc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
